#!/bin/bash
# --- Disk Devices ---
EFI_DISK="/dev/sde"
ROOT_DISK="/dev/nvme0n1"

# --- Partition sizes ---
EFI_SIZE="16G"
SWAP_SIZE="48G"

# --- Partition names ---
EFI_PART="${EFI_DISK}1"
SWAP_PART="${ROOT_DISK}p1"
ROOT_PART="${ROOT_DISK}p2"

# --- Mount Points ---
ROOT_MOUNTPOINT="/mnt/gentoo"
BTRFS_TEMP_MOUNT="/mnt/root"

# --- Mapper names ---
LUKS_ROOT_NAME="cryptroot"
LUKS_SWAP_NAME="cryptswap"

# --- System settings ---
HOSTNAME="gentoo-box"
TIMEZONE="Europe/Stockholm"
LOCALE="en_US.UTF-8 UTF-8"
KEYMAP="sv-latin1"

# --- Stage3 File ---
GENTOO_MIRROR='https://distfiles.gentoo.org'
STAGE3_VARIANT="hardened-selinux-openrc"
# The stage3 tarball to download and bootstrap
STAGE3_BASENAME="stage3-$GENTOO_ARCH-$STAGE3_VARIANT"
# The stage3 tarball to download and bootstrap (for edge cases where specific tarball names are required, such as for x32 architecture or x86 sub-architectures)
STAGE3_BASENAME_CUSTOM=$([[ $STAGE3_VARIANT == *x32* ]] && echo "stage3-$STAGE3_VARIANT" || echo "stage3-$GENTOO_SUBARCH-$STAGE3_VARIANT")

GENTOO_ARCH='amd64'
GENTOO_SUBARCH='amd64'

# --- Required by install.txt ---
I_HAVE_READ_AND_EDITED_THE_CONFIG_PROPERLY="true"
TMP_DIR="/tmp/gentoo-install"
GENTOO_INSTALL_REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GENTOO_INSTALL_REPO_BIND="/tmp/gentoo-install-repo"
GENTOO_INSTALL_REPO_DIR_ORIGINAL="$GENTOO_INSTALL_REPO_DIR"