#!/bin/bash
# --- Disk Devices ---
EFI_DISK="/dev/sde"
ROOT_DISK="/dev/nvme0n1"

# --- Partition sizes ---
EFI_SIZE="16G"
SWAP_SIZE="48G"

# --- Partition names ---
EFI_PART="${EFI_DISK}1"
SWAP_PART="${ROOT_DISK}p1"
ROOT_PART="${ROOT_DISK}p2"

# --- Mapper names ---
LUKS_ROOT_NAME="cryptroot"
LUKS_SWAP_NAME="cryptswap"

# --- System settings ---
HOSTNAME="gentoo-box"
TIMEZONE="Europe/Stockholm"
LOCALE="en_US.UTF-8 UTF-8"
KEYMAP="sv-latin1"